version: '3.8'
services:
  invoiceservice:
    image: thyseven/invoiceservice:dev
    ports:
      - "3005:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=invoiceservice
      - RabbitMQQueueName=MailQueue

  mailservice:
    image: thyseven/mailservice:dev
    ports:
      - "3010:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=mailservice
      - RabbitMQQueueName=MailQueue



networks:
  default:
    driver: bridge
    name: 'mitnet'