version: '3.8'
services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default
    volumes:
      - ./grafana-data:/var/lib/grafana
    restart: unless-stopped

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '15692:15692'
    hostname: rabbitmq
    container_name: dev-rabbit
    restart: unless-stopped


  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27018:27017
    networks:
      - default
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped

  vault_dev: 
    image: hashicorp/vault:latest
    restart: on-failure:10
    hostname: vault_dev
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201/'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201", "tls_disable": "0", "tls_cert_file":"/data/cert.pem", "tls_key_file":"/data/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '1a2b3c4d-5e6f-7g8h-9i0j-123456789abc'
      VAULT_TOKEN: 'abcdef12-3456-7890-abcd-ef1234567890'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-volume:/data
    networks:
      - default
    healthcheck:
      retries: 5
    command: 'server -dev -dev-root-token-id="1a2b3c4d-5e6f-7g8h-9i0j-123456789abc"'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - '9090:9090'
    networks:
      - default

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose: 
      - 8080
    restart: unless-stopped
    command: --interval 600
    networks:
      - default # or any other network like 'mitnet'


volumes:
  mongodb_data_container:


networks:
  default:
    driver: bridge
    name: 'mitnet'

