version: "3.8"
services:
  gronogolsentestingfrontend:
    platform: linux/amd64
    image: thyseven/gronogolsentestingfrontend:latest
    networks:
      - default

networks:
  default:
    driver: bridge
    name: 'mitnet'