version: "3.8"
services:
  invoiceservice:
    platform: linux/amd64
    image: thyseven/invoiceservice:dev
    ports:
      - "3005:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=invoiceservice
      - RabbitMQQueueName=MailQueue

  mailservice:
    platform: linux/amd64
    image: thyseven/mailservice:latest
    ports:
      - "3010:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=mailservice
      - RabbitMQQueueName=MailQueue

  userservice:
    platform: linux/amd64
    image: thyseven/userservice:dev
    ports:
      - "3015:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=userservice
      - RabbitMQQueueName=MailQueue

networks:
  default:
    driver: bridge
    name: "mitnet"
