version: "3.8"
services:
  invoiceservice:
    platform: linux/amd64
    image: thyseven/invoiceservice:dev
    ports:
      - "3005:3005"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=invoiceservice
      - RabbitMQQueueName=MailQueue
      - PublicIP=http://localhost:3005
      - ASPNETCORE_URLS=http://+:3005
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting


  mailservice:
    platform: linux/amd64
    image: thyseven/mailservice:dev
    ports:
      - "3010:3010"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=mailservice
      - RabbitMQQueueName=MailQueue
      - ASPNETCORE_URLS=http://+:3010
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

  userservice:
    platform: linux/amd64
    image: thyseven/userservice:dev
    ports:
      - "3015:3015"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=userservice
      - RabbitMQQueueName=MailQueue
      - ASPNETCORE_URLS=http://+:3015
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

  biddingservice:
    platform: linux/amd64
    image: thyseven/biddingservice:latest
    ports:
      - "3020:3020"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=biddingservice
      - RabbitMQQueueName=MailQueue
      - BiddingQueueName=BiddingQueue
      - ASPNETCORE_URLS=http://+:3020
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

  lotservice:
    platform: linux/amd64
    image: thyseven/lotservice:dev
    ports:
     - "3025:3025"
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=lotservice
      - RabbitMQQueueName=BiddingQueue
      - UserServiceEndpoint=userservice:3015
      - InvoiceServiceEndpoint=invoiceservice:3005
      - BiddingServiceEndpoint=biddingservice:3020
      - NginxEndpoint=nginx:3001
      - PublicIP=http://localhost:3025
      - ASPNETCORE_URLS=http://+:3025
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

  nginx:
      image: nginx:latest
      volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
      - invoiceservice
      - mailservice
      - userservice
      - biddingservice
      - lotservice
      ports:
      - "3001:3001"
      networks:
      - default
      restart: unless-stopped

networks:
  default:
    driver: bridge
    name: "mitnet"
