version: "3.8"
services:
  gronogolsentestingfrontend:
    platform: linux/amd64
    image: thyseven/gronogolsentestingfrontend:latest
    ports:
    - "3030:80"
    networks:
      - default
  gronogolsenui:
    platform: linux/amd64
    image: thyseven/gronogolsenui:latest
    ports:
      - "9987:5000"
    networks:
      - default


networks:
  default:
    driver: bridge
    name: 'mitnet'