version: '1.0'
services:
  vault_setup:
    platform: linux/amd64
    image: thyseven/vaultinitializer:latest
    environment:
      - VAULT_IP
      - VAULT_SECRET
      - JWTSecret=ThySeven2023PaddingToEnsureLengthAndSecurity123456
      - JWTIssuer=ThySevenIssuer
    networks:
      - default

networks:
  default:
    driver: bridge
    name: 'mitnet'