version: "3.8"
services:
  invoiceservice:
    platform: linux/amd64
    image: thyseven/invoiceservice:dev
    ports:
      - "3005:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=invoiceservice
      - RabbitMQQueueName=MailQueue
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting


  mailservice:
    platform: linux/amd64
    image: thyseven/mailservice:dev
    ports:
      - "3010:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=mailservice
      - RabbitMQQueueName=MailQueue
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

  userservice:
    platform: linux/amd64
    image: thyseven/userservice:dev
    ports:
      - "3015:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=userservice
      - RabbitMQQueueName=MailQueue
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

  biddingservice:
    platform: linux/amd64
    image: thyseven/biddingservice:latest
    ports:
      - "3020:8080"
    networks:
      - default
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=biddingservice
      - RabbitMQQueueName=MailQueue
      - BiddingQueueName=BiddingQueue
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

  lotservice:
    platform: linux/amd64
    image: thyseven/lotservice:dev
    ports:
     - "3025:8080"
    environment:
      - LokiEndpoint
      - RabbitMQHostName
      - VAULT_IP
      - VAULT_SECRET
      - MongoDBConnectionString
      - GrafanaHostname=lotservice
      - RabbitMQQueueName=BiddingQueue
      - UserServiceEndpoint=userservice:8080
      - InvoiceServiceEndpoint=invoiceservice:8080
      - BiddingServiceEndpoint=biddingservice:8080
      - PublicIP=localhost
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: any         # Restart under any failure condition
        delay: 10s              # Wait 5 seconds before restarting

networks:
  default:
    driver: bridge
    name: "mitnet"
